---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 600
    - name: "install node 12.X"
      shell: |
        curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
        sudo apt -y upgrade
        sudo apt install -y nodejs
    - name: "install python."
      become: true
      apt:
        name: ["python3"]
        state: latest
        update_cache: yes

    - name: "install pm2"
      become: true
      npm:
        name: pm2
        global: yes
        production: yes
        state: present

  roles:
    - configure-server
    - configure-prometheus-node-exporter